### ISSUE TITLE
stick footer on bottom

### ISSUE THREAD

**Issue by timnavigate** [timnavigate/timnavigate.com#8]
work example: https://github.com/hookex/red-star/commit/b55bd30e2973e425be215a872a53666bf17a6d4a

```css
body {
  display: flex;
  min-height: 100vh;
  flex-direction: column;
}

container {
  flex: 1;
}
```
